# Gerado pelo scaffolder; edite só o que precisar.
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: tourinho-labs/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
{%- if values.includeK8s %}
    backstage.io/kubernetes-id: ${{ values.name }}
    argocd/app-name: ${{ values.name }}
    kyverno.io/namespace: ${{ values.name }}
    kyverno.io/kind: Deployment,Pod
    kyverno.io/resource-name: ${{ values.name }}
{%- endif %}
  tags:
    - nodejs
    - fastify
{%- if values.includeK8s %}
    - kubernetes
{%- endif %}
  links:
    - url: https://github.com/tourinho-labs/${{ values.name }}
      title: Repositório
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
{%- if values.includeK8s %}
  dependsOn:
    - resource:default/policy-reporter
{%- endif %}
  # Descomente e aponte relações quando existirem.
  # dependsOn:
  #   - resource:postgresql
  # providesApis:
  #   - minha-api
