apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform-templates
  description: Platform Engineering templates (apps criadas na org tourinho-labs)
spec:
  targets:
    - ./catalog/systems.yaml
    - ./catalog/policy-reporter.yaml
    - ./templates/new-service/template.yaml
    - ./templates/new-service-full/template.yaml
    - ./templates/new-service-combo/template.yaml
    - ./templates/lambda/template.yaml
    - ./templates/service-day2/template.yaml
