apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-service
  title: New Service (1+1)
  description: Cria um novo serviço Fastify com CI e observabilidade. Registra automaticamente no catalog.
  tags:
    - nodejs
    - fastify
    - service
spec:
  owner: group:default/platform-engineering
  type: service

  parameters:
    - $yaml: ../_shared/params-service.yaml

  steps:
    - id: fetch
      name: Montar esqueleto
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ user.ref }}
          includeK8s: false

    - $yaml: ../_shared/step-publish.yaml

    - $yaml: ../_shared/step-register.yaml

  output:
    $yaml: ../_shared/output.yaml
