# Claim de provisionamento de banco (par do ExternalSecret db-conn).
apiVersion: platform.lab/v1alpha1
kind: AppDatabase
metadata:
  name: ${{ values.name }}-dev
  namespace: default
spec:
  appName: ${{ values.name }}
  env: dev
